### DISCUSSION TITLE
Using dark: in combination with rnr not working?

### DISCUSSION THREAD

**Discussion by nvsd** [founded-labs/react-native-reusables#192] [Q&A] [answered]
Is the `dark:*` modifier supposed to work? `bg-green-200 dark:bg-green-900` is always the dark variant.
Is there a way to get both approaches to work (dark: and the global CSS-defined themes?)

**Comment by mrzachnugent** [comment]
That could be a `tailwind.config.js`or `global.css` configuration issue. It could also be that you need to restart the app and clear the expo cache (`npx expo start --clear`).

Here is an example of a component that uses it: https://github.com/mrzachnugent/react-native-reusables/blob/main/packages/reusables/src/components/ui/data-table.tsx and here is the web demo of that component https://rnr-showcase.vercel.app/data-table

**Reply by nvsd** [reply]
Thanks for the reply and all of the work you've done with these components.

So I'm using the `global.css` here https://github.com/mrzachnugent/react-native-reusables/blob/main/apps/starter-base/global.css and the tailwind.config.js here https://github.com/mrzachnugent/react-native-reusables/blob/main/apps/starter-base/tailwind.config.js

Here's a quick video

https://github.com/user-attachments/assets/b5bdc6f8-8727-487e-8be1-019e01974701

The green rows you see have the classes `bg-green-200 dark:bg-green-900` and it doesn't change to the lighter shade in light mode.

The color scheme is set to `system` and I'm changing the color theme by using `command + shift + a` which is the key combo to "toggle appearance" in the ios simulator.

**Reply by nvsd** [reply]
Ok, so I got it to work, but I don't understand.

I found this https://github.com/shadcn-ui/ui/issues/515 and implemented a combination of the suggestions.
I removed the `darkMode` key from my `tailwind.config.js` file, and I also removed the `@layer base {...}` from `global.css`

`global.css`
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --background: 0 0% 100%;
  --foreground: 240 10% 3.9%;
  --card: 0 0% 100%;
  --card-foreground: 240 10% 3.9%;
  --popover: 0 0% 100%;
  --popover-foreground: 240 10% 3.9%;
  --primary: 240 5.9% 10%;
  --primary-foreground: 0 0% 98%;
  --secondary: 240 4.8% 95.9%;
  --secondary-foreground: 240 5.9% 10%;
  --muted: 240 4.8% 95.9%;
  --muted-foreground: 240 3.8% 46.1%;
  --accent: 240 4.8% 95.9%;
  --accent-foreground: 240 5.9% 10%;
  --destructive: 0 84.2% 60.2%;
  --destructive-foreground: 0 0% 98%;
  --border: 240 5.9% 90%;
  --input: 240 5.9% 90%;
  --ring: 240 5.9% 10%;
}

.dark:root {
  --background: 240 10% 3.9%;
  --foreground: 0 0% 98%;
  --card: 240 10% 3.9%;
  --card-foreground: 0 0% 98%;
  --popover: 240 10% 3.9%;
  --popover-foreground: 0 0% 98%;
  --primary: 0 0% 98%;
  --primary-foreground: 240 5.9% 10%;
  --secondary: 240 3.7% 15.9%;
  --secondary-foreground: 0 0% 98%;
  --muted: 240 3.7% 15.9%;
  --muted-foreground: 240 5% 64.9%;
  --accent: 240 3.7% 15.9%;
  --accent-foreground: 0 0% 98%;
  --destructive: 0 72% 51%;
  --destructive-foreground: 0 0% 98%;
  --border: 240 3.7% 15.9%;
  --input: 240 3.7% 15.9%;
  --ring: 240 4.9% 83.9%;
}
```
`tailwind.config.js`
```js
const { hairlineWidth } = require('nativewind/theme');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderWidth: {
        hairline: hairlineWidth(),
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
```
